### ISSUE TITLE
No image saved when ran.

### ISSUE THREAD

**Issue by graykevinb** [juangallostra/Landscape_generator#2]
I ran your code in python 2 multiple times and found no testing.png image.

**Comment by juangallostra** [comment]
@graykevinb is the program giving any error or simply just not saving the image? I'm running the code on Windows 10 and I am getting the images correctly. Which OS are you running? It should save the image in the directory were the code is located.

**Comment by graykevinb** [comment]
I'm running the Fedora 25, which is Linux. The exact python version I ran it as was 2.7. There is no errors at all. Perhaps the method you used to save the image is windows only? 

On January 18, 2017, at 4:52 AM, Juan Gallostra Acín <notifications@github.com> wrote:

@graykevinb is the program giving any error or simply just not saving the image? I'm running the code on Windows 10 and I am getting the images correctly. Which OS are you running? It should save the image in the directory were the code is located.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/juangallostra/Landscape_generator","title":"juangallostra/Landscape_generator","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/juangallostra/Landscape_generator">https://github.com/juangallostra/Landscape_generator</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@juangallostra in #2: @graykevinb is the program giving any error or simply just not saving the image? I'm running the code on Windows 10 and I am getting the images correctly. Which OS are you running? It should save the image in the directory were the code is located."}],"action":{"name":"View Issue","url":"<a href="https://github.com/juangallostra/Landscape_generator/issues/2#issuecomment-273444729">https://github.com/juangallostra/Landscape_generator/issues/2#issuecomment-273444729</a>"}}}

**Comment by juangallostra** [comment]
@graykevinb I don't think so. To get the directory where the image should be saved I'm calling os.getcwd() which doesn't depend on the platform it is being used on. To save the image I'm using the method provided by PIL which should also work.

Maybe it has something to do with privileges? 

Try changing line 125: 
landscape.save(os.getcwd()+'\\testing.png')
by:
landscape.show()

It should show the image instead of saving it. If this works, then the problem has to do with saving the image. If it doesn't, the problem might be in generating it.

**Comment by graykevinb** [comment]
I apologize for my late reply. I think it was an os bug, they now have appeared and it now works. Thanks for your time. Again sorry for the late reply. Also awesome script!
